### ISSUE TITLE
flask-admin + flask-zurb-foundation

### ISSUE THREAD

**Issue by xmnlab** [ondoheer/flask-zurb-foundation#2]
Hi,

I'm new with flask-admin and I'm trying to use it with flask-zurb-foundation 

have you have some exemple working with this 2 libs?

Thank you.

My best regards

**Comment by ondoheer** [comment]
Hi xmnfw,

Flask-Admin comes with it's own css and ussually people just extend from it, still. it is so well thought that it allows to overide it's base template for one of your own, thus allowing you to use for example, zurb-foundation. 

[Here is howto](https://flask-admin.readthedocs.org/en/v1.0.9/templates/#customizing-templates),

basically initialize the admin plugion like this:

```
admin = Admin(app, base_template="foundation/base.html" 
```

or as I would, just linking to another admin_base.html you build specifically for this purpose (using the suggested blocks) and that has "foundation/base.html" as iit's own base.
