### ISSUE TITLE
Provide WTForms support 

### ISSUE THREAD

**Issue by algarni** [ondoheer/flask-zurb-foundation#3]
Create forms and validation are very easy with WTForms. I hope that flask-zurb-foundation will support WTForms soon.

**Comment by ondoheer** [comment]
Forms in Foundation aren't complicated at all, they don't use any special classes or group items in a specific way like they do in Bootstrap, that is why I didin't include ant macros for them. I thought to add them until I realized I preffer to have total control over how the form comes out, so you can use WTForms directly in your templates ad you would with any Python project
